export const BASE_URL = "http://codingcase.zeiss.services"
export const WS_BASE_URL = "ws://codingcase.zeiss.services"
export const MACHINES_URL = "/api/v1/machines"
export const MACHINES_DETAIL_URL = "/api/v1/machines"
export const WS_ENDPOINT = "/ws"